require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/generators/**/*'
    - 'lib/rails/**/*'
    - 'lib/templates/**/*'
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'spec/requests/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/invitations_controller.rb'

Style/Documentation:
  Enabled: false