# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    
    environment:
      CC_TEST_REPORTER_ID: 5a1e999d1d8a3629fdd50273f3d95d9a874fe9dd58246e0071c96cdda89cc7d0
      
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mongo:3.6.6-jessie
      
    working_directory: ~/davedkg-rails-template
    
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      
      # # install test reporter
      # - run:
      #   name: Setup Code Climate test-reporter Dependencies
      #   command: |
      #     sudo composer self-update
      #     composer install -n --prefer-dist
      # - run:
      #   name: Setup Code Climate test-reporter
      #   command: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter

      # bundle install
      - restore_cache:
          keys:
            - davedkg-rails-template-bundle-v2-{{ checksum "Gemfile.lock" }}
            - davedkg-rails-template-bundle-v2-
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: davedkg-rails-template-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # yarn install
      - restore_cache:
          keys:
            - davedkg-rails-template-yarn-{{ checksum "yarn.lock" }}
            - davedkg-rails-template-yarn-
      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: davedkg-rails-template-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
    
      - run:
          name: rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      # collect reports
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results

notify:
  webhooks:
    # - url: https://hooks.slack.com/services/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
