version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1
  node: circleci/node@5.2.0

executors:
  rails-executor:
    docker:
      - image: cimg/ruby:3.3.6-browsers
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_DB: davedkg_template_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: db_user
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: db_user
      RAILS_ENV: test
  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.6-browsers
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"

jobs:
  build:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
  rspec:
    executor:
      name: rails-executor
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '22.3.0'
      - run:
          name: Wait for DB to Boot
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rake db:schema:load db:seed --trace
      - run:
          name: Compile Assets
          command: bundle exec rake assets:precompile
      - ruby/rspec-test
  rubocop:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rubocop -c .rubocop.yml
  brakeman:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec brakeman
  fasterer:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec fasterer -c .fasterer.yml
  importmap_audit:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bin/importmap audit
  importmap_outdated:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bin/importmap outdated

workflows:
  version: 2
  test:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - brakeman:
          requires:
            - build
      - fasterer:
          requires:
            - build
      - importmap_audit:
          requires:
            - build
          filters: |
            pipeline.git.branch != "main"
      - importmap_outdated:
          requires:
            - build
          filters: |
            pipeline.git.branch != "main"
