version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

executors:
  rails-executor:
    docker:
      - image: cimg/ruby:3.3.0-browsers
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_DB: davedkg_template_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: db_user
      - image: cimg/redis:6.2.6
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: db_user
      RAILS_ENV: test
      REDIS_URL: redis://127.0.0.1:6379/0
  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.0-browsers
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"

jobs:
  build:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps

  rspec:
    executor:
      name: rails-executor
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB to Boot
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rake db:schema:load db:seed --trace
      - ruby/rspec-test

  reek:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec reek -c .reek.yml

  rubocop:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rubocop -c .rubocop.yml

  brakeman:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec brakeman

  fasterer:
    executor:
      name: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec fasterer

workflows:
  version: 2
  test:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - reek:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - brakeman:
          requires:
            - build
      - fasterer:
          requires:
            - build